### PR TITLE
Echidna Test

### PR DESCRIPTION
**Pull request by naszam**
# Description: 
https://app.clubhouse.io/scdomaincommunityteam/story/10021/echidna-test-on-l2

COB Team Name or Author(s): @naszam

Fuzz:
You will need to install [echidna](https://github.com/crytic/echidna) separately, and then run:
```echidna-test contracts/invariants/DaiInvariant.sol --contract DaiInvariant --config echidna.config.yml```

# Contribution Checklist
- [ ] PR title ends with (SC-<TICKET_NUMBER>)
- [x] Link to clubhouse ticket
- [ ] Code approved
- [ ] Tests approved
- [ ] CI Tests pass

### CODE REVIEW

**Comment by hexonaut** [comment]
If these are test contracts could you put them in the `contracts/test` dir?

**Comment by naszam** [comment]
They usually go in the contracts directory, to keep the import path clean.
Anyway, if you prefer to move the invariants directory in tests and add a yarn fuzz script is ok for me.

**Comment by naszam** [comment]
> If these are test contracts could you put them in the `contracts/test` dir?

Sure! I can move the invariants directory to `contracts/`

**Comment by hexonaut** [comment]
Looks good to me as soon as `contracts/invariants/DaiInvariant.sol` is moved to `contracts/test/DaiInvariant.sol`

**Pull request merged**
